config/routes.rb
Rails.application.routes.draw do
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products, only: [:new, :edit, :destroy, :create, :update]

  get "/product/search" => "products#search", as: :search_product
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :department

  validates :quantity , presence: true
  validates :name , length: {minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
      @products = Product.all.order :name\
  end

  def new
    @product = Product.new
    set_departments
  end

  def create

    @product = Product.new product_params
    if @product.save
      flash[:notice] = "Produto salvo com sucesso"
      redirect_to root_url
    else
      render_view :new
    end
  end

  def edit
    set_product
    @departments = Department.all
  end

  def update
    set_product
    if @product.update product_params
      flash[:notice] = "alterado com sucesso"
      redirect_to root_url
    else
      render_view :view
    end
  end

  def destroy
    set_product
    @product.destroy
    redirect_to root_url
  end

  def search
    @name = params[:nome]
    @products = Product.where "name like ?", "%#{@name}%"
  end

  private

  def set_product
    id = params[:id]
    @product = Product.find id
  end

  def set_departments
    @departments = Department.all
  end


  def render_view(view_name)
    @departments = Department.all
    render view_name
  end

  def product_params
    params.required(:product).permit :name, :description, :quantity, :price, :department_id
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/departments/_form.html.erb
<%= form_with(model: department, local: true) do |form| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :department_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShirtsStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= nav_bar fixed: :top, brand: "Learning Rails", brand_link: root_url do %>
    <%= form_tag search_product_path, method: :get, class: "navbar-form navbar-right" do %>
      <div class="form-group">
        <%= text_field_tag :nome, @name, class: "form-control" %>
        <%= button_to "Buscar", nil, class: "btn btn-default" %>
      </div>
    <% end %>
  <% end %>
  <div class="container" style="margin-top: 60px">
    <%= yield %>
  </div>
  </body>
</html>

app/views/products/_form.html.erb
<div style="height: 60px">

</div>

<% @product.errors.full_messages.each do |m| %>
    <div class="alert alert-danger" role="alert"><%=m%></div>
<% end %>

<%= form_for @product do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control", step: 0.1 %>
    </div>
    <div class="form-group">
      <%= f.label :quantity %>
      <%= f.number_field :quantity, class: "form-control", step: 2 %>
    </div>
    <div class="form-group">
      <%= f.label :department %>
      <%= f.collection_select :department_id, @departments, :id, :name, {}, class: "form-control" %>
    </div>

    <%= submit_tag btn_label, class: "btn btn-primary" %>
<% end %>

app/views/products/_products.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%=flash[:notice]%></div>
<% end %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>
      nome
    </th>
    <th>descriçao</th>
    <th>preço</th>
    <th>quantidade</th>
  </tr>
  </thead>
  <tbody class="table-hover">
  <% for p in @products %>
      <tr>
        <td>
          <%= p.name %>
        </td>
        <td>
          <%= p.description %>
        </td>
        <td>
          <%= p.price %>
        </td>
        <td>
          <%= p.quantity %>
        </td>
        <td>
          <%= button_to "Delete", p , method: :delete, class: "btn btn-danger", data: {confirm: "quer deletar o #{p.name}"} %>
        </td>
        <td>
          <%= button_to "Edit", edit_product_path(p.id), method: :get, class: "btn btn-default" %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "criar novo", new_product_path %>

app/views/products/edit.html.erb
<%= render partial: "form", locals: {btn_label: 'Edit Product'} %>

app/views/products/index.html.erb
<%= render partial: 'products' %>

app/views/products/new.html.erb
<%= render partial: "form", locals: {btn_label: 'Create Product'} %>

app/views/products/search.html.erb
<%= render partial: 'products' %>

app/views/products/update.html.erb
updated